#!/usr/bin/env bash
#first make tabbed version
./vehicles2tabbed > tabbed
#then, generate random data
./rnd.py > rnddata

#then, cat and shuffle, file will be "vehicles-new"

cat tabbed rnddata |  shuf > vehicles-new


