#!/usr/bin/env bash
[ -n "$1" ] && export VFILE="$1" || export VFILE="../mystery/vehicles"

cat $VFILE |\
#skip header
    tail -$(expr $(cat $VFILE | wc -l) - 4) |\
# hack to switch lines to -
    tr '\n' '-' |\
# to change the double newline (end or record) to newlines
    sed 's/--/\n/g' |\
# and last, single new lines to tabs
    sed 's/-/\t/g'
